# Generated by Django 2.2.5 on 2019-11-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0003_auto_20191120_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitstatus',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruits.Master'),
        ),
    ]
