# Generated by Django 2.2.5 on 2019-12-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0005_auto_20191206_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='recruitstatus',
            name='recruit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recruits.Recruit'),
        ),
    ]
